server_name: "${DOMAIN}"
pid_file: /data/homeserver.pid
public_baseurl: "https://matrix.${DOMAIN}"

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['0.0.0.0']
    resources:
      - names: [client, federation]
        compress: false

database:
  name: sqlite3
  args:
    database: /data/homeserver.db

log_config: "/data/log.config"

media_store_path: "/data/media"
uploads_path: "/data/uploads"
registration_shared_secret: "${MATRIX_REGISTRATION_SHARED_SECRET}"
macaroon_secret_key: "${MATRIX_MACAROON_SECRET_KEY}"

enable_registration: false
enable_registration_without_verification: false

trusted_key_servers:
  - server_name: "matrix.org"

retention:
  enabled: true
  default_policy:
    min_lifetime: 1d
    max_lifetime: 365d

url_preview_enabled: false
max_upload_size: "50M"
max_spider_size: "10M"

rc_messages_per_second: 0.2
rc_message_burst_count: 10.0

rc_registration:
  per_second: 0.17
  burst_count: 3

rc_login:
  address:
    per_second: 0.17
    burst_count: 3
  account:
    per_second: 0.17
    burst_count: 3
  failed_attempts:
    per_second: 0.17
    burst_count: 3

federation_rc_window_size: 1000
federation_rc_sleep_limit: 10
federation_rc_sleep_delay: 500
federation_rc_reject_limit: 50
federation_rc_concurrent: 3

experimental_features:
  spaces_enabled: true
